#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CAS")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertCAS_Activity(CAS_Activity instance);
  partial void UpdateCAS_Activity(CAS_Activity instance);
  partial void DeleteCAS_Activity(CAS_Activity instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CASConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<CAS_Activity> CAS_Activities
	{
		get
		{
			return this.GetTable<CAS_Activity>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CAS_Activity")]
public partial class CAS_Activity : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Srl;
	
	private string _Title;
	
	private string _Description;
	
	private System.Nullable<int> _Srl_Erae;
	
	private string _RegDate;
	
	private string _DeadlineDate;
	
	private string _DeadlineTime;
	
	private System.Nullable<double> _FinalPercent;
	
	private System.Nullable<double> _Grade;
	
	private System.Nullable<bool> _IsActive;
	
	private string _DocumentFile;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSrlChanging(int value);
    partial void OnSrlChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnSrl_EraeChanging(System.Nullable<int> value);
    partial void OnSrl_EraeChanged();
    partial void OnRegDateChanging(string value);
    partial void OnRegDateChanged();
    partial void OnDeadlineDateChanging(string value);
    partial void OnDeadlineDateChanged();
    partial void OnDeadlineTimeChanging(string value);
    partial void OnDeadlineTimeChanged();
    partial void OnFinalPercentChanging(System.Nullable<double> value);
    partial void OnFinalPercentChanged();
    partial void OnGradeChanging(System.Nullable<double> value);
    partial void OnGradeChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    partial void OnDocumentFileChanging(string value);
    partial void OnDocumentFileChanged();
    #endregion
	
	public CAS_Activity()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Srl", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Srl
	{
		get
		{
			return this._Srl;
		}
		set
		{
			if ((this._Srl != value))
			{
				this.OnSrlChanging(value);
				this.SendPropertyChanging();
				this._Srl = value;
				this.SendPropertyChanged("Srl");
				this.OnSrlChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100)")]
	public string Title
	{
		get
		{
			return this._Title;
		}
		set
		{
			if ((this._Title != value))
			{
				this.OnTitleChanging(value);
				this.SendPropertyChanging();
				this._Title = value;
				this.SendPropertyChanged("Title");
				this.OnTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(500)")]
	public string Description
	{
		get
		{
			return this._Description;
		}
		set
		{
			if ((this._Description != value))
			{
				this.OnDescriptionChanging(value);
				this.SendPropertyChanging();
				this._Description = value;
				this.SendPropertyChanged("Description");
				this.OnDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Srl_Erae", DbType="Int")]
	public System.Nullable<int> Srl_Erae
	{
		get
		{
			return this._Srl_Erae;
		}
		set
		{
			if ((this._Srl_Erae != value))
			{
				this.OnSrl_EraeChanging(value);
				this.SendPropertyChanging();
				this._Srl_Erae = value;
				this.SendPropertyChanged("Srl_Erae");
				this.OnSrl_EraeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegDate", DbType="NChar(10)")]
	public string RegDate
	{
		get
		{
			return this._RegDate;
		}
		set
		{
			if ((this._RegDate != value))
			{
				this.OnRegDateChanging(value);
				this.SendPropertyChanging();
				this._RegDate = value;
				this.SendPropertyChanged("RegDate");
				this.OnRegDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeadlineDate", DbType="NChar(10)")]
	public string DeadlineDate
	{
		get
		{
			return this._DeadlineDate;
		}
		set
		{
			if ((this._DeadlineDate != value))
			{
				this.OnDeadlineDateChanging(value);
				this.SendPropertyChanging();
				this._DeadlineDate = value;
				this.SendPropertyChanged("DeadlineDate");
				this.OnDeadlineDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeadlineTime", DbType="NChar(8)")]
	public string DeadlineTime
	{
		get
		{
			return this._DeadlineTime;
		}
		set
		{
			if ((this._DeadlineTime != value))
			{
				this.OnDeadlineTimeChanging(value);
				this.SendPropertyChanging();
				this._DeadlineTime = value;
				this.SendPropertyChanged("DeadlineTime");
				this.OnDeadlineTimeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinalPercent", DbType="Float")]
	public System.Nullable<double> FinalPercent
	{
		get
		{
			return this._FinalPercent;
		}
		set
		{
			if ((this._FinalPercent != value))
			{
				this.OnFinalPercentChanging(value);
				this.SendPropertyChanging();
				this._FinalPercent = value;
				this.SendPropertyChanged("FinalPercent");
				this.OnFinalPercentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grade", DbType="Float")]
	public System.Nullable<double> Grade
	{
		get
		{
			return this._Grade;
		}
		set
		{
			if ((this._Grade != value))
			{
				this.OnGradeChanging(value);
				this.SendPropertyChanging();
				this._Grade = value;
				this.SendPropertyChanged("Grade");
				this.OnGradeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
	public System.Nullable<bool> IsActive
	{
		get
		{
			return this._IsActive;
		}
		set
		{
			if ((this._IsActive != value))
			{
				this.OnIsActiveChanging(value);
				this.SendPropertyChanging();
				this._IsActive = value;
				this.SendPropertyChanged("IsActive");
				this.OnIsActiveChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DocumentFile", DbType="NVarChar(500)")]
	public string DocumentFile
	{
		get
		{
			return this._DocumentFile;
		}
		set
		{
			if ((this._DocumentFile != value))
			{
				this.OnDocumentFileChanging(value);
				this.SendPropertyChanging();
				this._DocumentFile = value;
				this.SendPropertyChanged("DocumentFile");
				this.OnDocumentFileChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
